DU client
streamr-dev/data-union pull request #182
Opened 2022-04-27 16:44 UTC by timoxley

2022-05-05 09:55 UTC, kare commented on packages/client/src/DataUnionClient.ts
> +            c .resolve<LoginEndpoints>(LoginEndpoints),
Space typo

2022-05-06 08:40 UTC, timoxley commented on packages/client/src/DataUnionClient.ts
> +            c .resolve<LoginEndpoints>(LoginEndpoints),
Good spotting

2022-05-12 08:07 UTC, tumppi commented
Tried alpha.3 in core-frontend project and got error below. Is this a known issue? This happens after I add the import without even using it.

```
ERROR in ./node_modules/@dataunions/client/web/index.js 25608:37
Module parse failed: Unexpected token (25608:37)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   }
|   getAllProviders() {
>     if (!this.ethereumConfig.network?.rpcs || !this.ethereumConfig.network?.rpcs?.length) {
|       return [getDefaultProvider()];
|     }
 @ ./src/marketplace/modules/dataUnion/services.js 11:0-49
 @ ./src/marketplace/containers/EditProductPage/DeployDataUnionModal.jsx
 @ ./src/userpages/components/DataUnionPage/index.jsx
 @ ./src/app/Userpages.jsx
 @ ./src/app/index.jsx
 @ ./src/index.jsx
 @ multi ./src/shared/utils/diagnostics.js ./src/setup.js ./src/index.jsx
```

2022-05-12 09:04 UTC, jtakalai requested changes
We should do a walkthrough of some of the mechanisms that come from StreamrClient, esp. the tsyringe/DI stuff

2022-05-12 09:04 UTC, jtakalai commented on scripts/copyAbis.sh
>  jq .abi artifacts/contracts/DataUnionFactorySidechain.sol/DataUnionFactorySidechain.json > ../dataunion-thegraph-subgraph/abis/DataUnionFactorySidechain.json
these still have old directory names

2022-05-12 09:04 UTC, jtakalai commented on scripts/generateYaml.sh
> -#!/bin/bash
what mechanism replaced this in subgraph yaml generation? When new local deployment is done, those yaml need to be re-generated to match the new addresses...

2022-07-21 17:35 UTC, merged